# Generated by Django 4.2.3 on 2023-07-24 11:43

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarShowroomCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "CarShowroomCar",
                "verbose_name_plural": "CarShowroomsCars",
                "db_table": "car_showroom_car",
            },
        ),
        migrations.CreateModel(
            name="CarShowroomDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("discount_start", models.DateField()),
                ("discount_end", models.DateField()),
                ("description", models.CharField(max_length=500, null=True)),
            ],
            options={
                "verbose_name": "CarShowroomDiscount",
                "verbose_name_plural": "CarShowroomsDiscounts",
                "db_table": "car_showroom_discount",
                "ordering": ["discount_start"],
            },
        ),
        migrations.CreateModel(
            name="CarShowroomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(default="US", max_length=2),
                ),
                ("car_characteristics", models.JSONField(default=dict)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=19),
                ),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "CarShowroom",
                "verbose_name_plural": "CarShowrooms",
                "db_table": "carshowroom",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarShowroomSupplierPurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("cars_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "CarShowroomSupplierPurchaseHistory",
                "verbose_name_plural": "CarShowroomSupplierPurchaseHistories",
                "db_table": "car_showroom_purchase_history",
            },
        ),
    ]
