# Generated by Django 4.2.3 on 2023-07-18 09:48

import apps.core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierCarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.carmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "SupplierCar",
                "verbose_name_plural": "SupplierCars",
                "db_table": "supplier_car",
            },
        ),
        migrations.CreateModel(
            name="SupplierModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("created_year", models.DateField()),
                ("count_of_customers", models.PositiveIntegerField(default=0)),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=19),
                ),
                (
                    "cars_list",
                    models.ManyToManyField(
                        through="suppliers.SupplierCarModel", to="core.carmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "supplier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("discount_start", models.DateField(default=django.utils.timezone.now)),
                (
                    "discount_end",
                    models.DateField(default=apps.core.models.discount_end_distance),
                ),
                ("description", models.CharField(max_length=500, null=True)),
                ("car_model", models.ManyToManyField(to="core.carmodel")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="suppliers.suppliermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "SupplierDiscount",
                "verbose_name_plural": "SupplierDiscounts",
                "db_table": "supplier_discount",
                "ordering": ["discount_start"],
            },
        ),
        migrations.AddField(
            model_name="suppliercarmodel",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="suppliers.suppliermodel",
            ),
        ),
    ]
