# Generated by Django 4.2.3 on 2023-07-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "max_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("car_char", models.JSONField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="customers.customermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "CustomerOffer",
                "verbose_name_plural": "CustomersOffers",
                "db_table": "customer_offer",
                "ordering": ("created",),
            },
        ),
    ]
